&lt;!DOCTYPE html&gt;
&lt;html&gt;
  &lt;head&gt;
    &lt;meta http-equiv="Content-type" content="text/html; charset=UTF-8" /&gt;
    &lt;title&gt;Snake game&lt;/title&gt;
    &lt;link rel="stylesheet" type="text/css" href="css/main.css" /&gt;
    &lt;script language="javascript" type="text/javascript" src="http://code.jquery.com/jquery-2.0.3.min.js"&gt;&lt;/script&gt;
    &lt;script language="javascript" type="text/javascript" src="js/table.js"&gt;&lt;/script&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;h1&gt;Welcome to my dynamic table creator!&lt;/h1&gt;
    &lt;p&gt;Size of grid: &lt;input id="input" type="text"&gt;&lt;/p&gt;
    &lt;button id="button" type="button"&gt;Create Table&lt;/button&gt;
  &lt;/body&gt;
&lt;/html&gt;